
server:
  port: 8081 

spring:
  application:
    name: USER-CLIENT

  datasource:
    url: jdbc:mysql://localhost:3306/User_Microservice
    username: root
    password: Umesh123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQLDialect
        format_sql: true

logging:
  level:
    com.successive.UserService.service: trace

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,circuitbreakers

  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:

      ratingServiceBreaker:
        registerHealthIndicator: true    # This enables the circuit breaker to be monitored via Spring Boot Actuator's health endpoint.

        slidingWindowSize: 10            # Number of calls to consider for calculating the failure rate percentage     
        failureRateThreshold: 50         # Percentage of failures to trigger the circuit breaker
        minimumNumberOfCalls: 5          # Minimum number of calls before the circuit breaker can calculate the failure rate
        waitDurationInOpenState: 10s     # Time to wait before transitioning from OPEN to HALF_OPEN state
  

      hotelServiceBreaker:
        registerHealthIndicator: true      # This enables the circuit breaker to be monitored via Spring Boot Actuator's health endpoint.

        slidingWindowSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
